#ifndef HTML_ACTION_H
#define HTML_ACTION_H

#define HTML_ACTION_NONE   0
#define HTML_ACTION_AUTO   1
#define HTML_ACTION_INLINE 2
#define HTML_ACTION_JAVASCRIPT 3
#define HTML_ACTION_JAVASCRIPT_BLOCK 4
#define HTML_ACTION_MAIN_JAVASCRIPT_BLOCK 5
#define HTML_ACTION_PHP_BLOCK 6
#define HTML_ACTION_CSS_BLOCK 7

#endif // HTML_ACTION

